ECOLENS/ecolens/ecolens/urls.py
from django.contrib import admin
from django.urls import include, path

from .views import home_view, about_view

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("", home_view, name="home"),
    path("about/", about_view, name="about"),
    path("vehicle_usages/", include("vehicle_usages.urls")),
    path("household_usages/", include("household.urls")),
    path("food/", include("food.urls")),
    path("carbon_footprint/", include("carbon_footprint.urls")),
    path("consumer_good/", include("consumer_good.urls")),
    path("other/", include("other.urls")),
    path("travel/", include("travel.urls")),
    path("", include("general.urls")),
    path("accounts/", include("accounts.urls")),
]

ECOLENS/ecolens/food/urls.py
from django.urls import path
from food.views import (
    # calss based views
    FoodConsumptionCreateView,
    FoodConsumptionDetailView,
    FoodConsumptionListView,
    FoodConsumptionUpdateView,
    FoodConsumptionDeleteView,
)


app_name = "food"
urlpatterns = [
    path(
        "",
        FoodConsumptionListView.as_view(),
        name="food_consumption_list",
    ),
    path(
        "<int:pk>",
        FoodConsumptionDetailView.as_view(),
        name="detail",
    ),
    path(
        "create",
        FoodConsumptionCreateView.as_view(),
        name="food_consumption_create",
    ),
    path(
        "<int:pk>/update",
        FoodConsumptionUpdateView.as_view(),
        name="household_consumption_update",
    ),
    path(
        "<int:pk>/delete",
        FoodConsumptionDeleteView.as_view(),
        name="household_consumption_delete",
    ),
]

ECOLENS/ecolens/food/models.py
from django.db import models
from django.urls import reverse
from food.choices import (
    CO2EmissionUnit,
    DietType,
    ConsumptionLabel,
    WasteLabel,
)
from food.utils import (
    FOOD_TYPE_CONVERSION_FACTORS,
    FOOD_CONSUMPTION_CONVERSION_FACTORS,
    WASTE_LABEL_CONVERSION_FACTORS,
)
from django.core.exceptions import ValidationError

from general.models import General


def validate_wastage_label(value):
    if value < 0.0 or value > 1.0:
        raise ValidationError("Invalid input. Input must be between 0 and 1.")


class FoodConsumption(models.Model):
    id = models.AutoField(primary_key=True)
    diet_type = models.CharField(
        max_length=2,
        choices=DietType.choices,
        default=DietType.VI,
        blank=False,
    )

    consumption_level = models.CharField(
        max_length=8,
        choices=ConsumptionLabel.choices,
        default=ConsumptionLabel.LWC,
        blank=False,
        help_text="""Select the appropriate waste category based on the percentage.""",
    )

    level_of_wastage = models.FloatField(
        default=0.0,
        validators=[validate_wastage_label],
        help_text="e.g. 0.3 to represent 30%",
        blank=False,
    )
    consumption_unit = models.CharField(
        max_length=12,
        choices=CO2EmissionUnit.choices,
        default=CO2EmissionUnit.TCO2_Y,
        blank=False,
    )

    general = models.ForeignKey(General, on_delete=models.CASCADE)

    # CALCULATED FILDS
    diet_emission = models.FloatField(default=0)
    diet_emission_unit = models.CharField(
        max_length=12,
        choices=CO2EmissionUnit.choices,
        default=CO2EmissionUnit.TCO2,
        blank=False,
    )
    wastage_emission = models.FloatField(default=0)
    wastage_emission_unit = models.CharField(
        max_length=12,
        choices=CO2EmissionUnit.choices,
        default=CO2EmissionUnit.TCO2,
        blank=False,
    )

    food_footprint = models.FloatField(default=0)
    food_footprint_unit = models.CharField(
        max_length=12,
        choices=CO2EmissionUnit.choices,
        default=CO2EmissionUnit.TCO2,
        blank=False,
    )

    def save(self, *args, **kwargs):

        self.diet_emission = (
            FOOD_TYPE_CONVERSION_FACTORS[self.diet_type]
            * FOOD_CONSUMPTION_CONVERSION_FACTORS[self.consumption_level]
            * self.general.num_people
        )
        self.wastage_emission = (
            0.564290
            * FOOD_CONSUMPTION_CONVERSION_FACTORS[self.consumption_level]
            * self.level_of_wastage
            * self.general.num_people
        )
        self.food_footprint = self.diet_emission + self.wastage_emission
        super().save(*args, **kwargs)

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})  # f"/household/{self.pk}"

ECOLENS/ecolens/travel/models.py
# from django.db import models

# Create your models here.
from django.db import models
from django.utils import timezone

from django.db import models
from django.utils import timezone
from django.urls import reverse
from ecolens.custom_choices import DistanceUnit, CO2EmissionUnit
from ecolens.custom_validators import validate_min, validate_distance_unit
from .utils import (
    BUSINESS_FLIGHT_DISTANCE_CONVERSION_FACTORS,
    BUSINESS_PUBLIC_TRNSIT_CONVERSION_FACTORS,
    BUSINESS_GASOLINE_CAR_MANUFACTURING_EMISSIONS,
    BUSINESS_DIESEL_CAR_MANUFACTURING_EMISSIONS,
    BUSINESS_ELECTRIC_CAR_MANUFACTURING_EMISSIONS,
    BUSINESS_HYBRID_CAR_MANUFACTURING_EMISSIONS,
    BUSINESS_ELECTRIC_CAR_EMISSIONS_PER_KM,
    BUSINESS_HYBRID_CAR_EMISSIONS_PER_KM,
    BUSINESS_GASOLINE_CAR_EMISSIONS_PER_KM,
    BUSINESS_DISEL_CAR_EMISSIONS_PER_KM,
    BUSINESS_ELECTRIC_CAR_EMISSIONS_PER_KM,
    BUSINESS_HYBRID_CAR_EMISSIONS_PER_KM,
    STAFF_GASOLINE_CAR_EMISSIONS_PER_KM,
    STAFF_DISEL_CAR_EMISSIONS_PER_KM,
    STAFF_ELECTRIC_CAR_EMISSIONS_PER_KM,
    STAFF_HYBRID_CAR_EMISSIONS_PER_KM,
)


class Transport(models.Model):
    id = models.AutoField(primary_key=True)
    flight_distance = models.FloatField(
        default=0,
        validators=[validate_min],
        help_text="e.g., 1000",
    )
    flight_unit = models.CharField(
        max_length=2,
        choices=DistanceUnit.choices,
        default=DistanceUnit.Km,
        blank=False,
        validators=[validate_distance_unit],
    )

    public_transit_distance = models.FloatField(
        default=0,
        validators=[validate_min],
        help_text="e.g., 1000",
    )
    transit_unit = models.CharField(
        max_length=2,
        choices=DistanceUnit.choices,
        default=DistanceUnit.Km,
        blank=False,
        validators=[validate_distance_unit],
    )

    # No of cars- Company Vehicles
    company_num_of_gasolin_cars = models.IntegerField(default=0, help_text="e.g., 1")
    company_num_of_diesel_cars = models.IntegerField(default=0, help_text="e.g., 1")
    company_num_of_electric_cars = models.IntegerField(default=0, help_text="e.g., 1")
    company_num_of_hybrid_cars = models.IntegerField(default=0, help_text="e.g., 1")

    # Car Milage - Company Vehicles
    company_gasoline_car_driven = models.FloatField(default=0, help_text="e.g., 100")
    company_diesel_car_driven = models.FloatField(default=0, help_text="e.g., 100")
    company_electric_car_driven = models.FloatField(default=0, help_text="e.g., 100")
    company_hybrid_car_driven = models.FloatField(default=0, help_text="e.g., 100")

    # Car Milage - Staff Commute
    staff_gasoline_car_driven = models.FloatField(default=0, help_text="e.g., 100")
    staff_diesel_car_driven = models.FloatField(default=0, help_text="e.g., 100")
    staff_electric_car_driven = models.FloatField(default=0, help_text="e.g., 100")
    staff_hybrid_car_driven = models.FloatField(default=0, help_text="e.g., 100")

    # Car Milage Unit - Company Vehicles
    gasolin_car_unit = models.CharField(
        max_length=2,
        choices=DistanceUnit.choices,
        default=DistanceUnit.Km,
        blank=False,
        validators=[validate_distance_unit],
    )
    diesel_car_unit = models.CharField(
        max_length=2,
        choices=DistanceUnit.choices,
        default=DistanceUnit.Km,
        blank=False,
        validators=[validate_distance_unit],
    )
    electric_car_unit = models.CharField(
        max_length=2,
        choices=DistanceUnit.choices,
        default=DistanceUnit.Km,
        blank=False,
        validators=[validate_distance_unit],
    )
    hybrid_car_unit = models.CharField(
        max_length=2,
        choices=DistanceUnit.choices,
        default=DistanceUnit.Km,
        blank=False,
        validators=[validate_distance_unit],
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # CALCULATED FILDS
    flight_emission = models.FloatField(default=0)
    public_transit_emission = models.FloatField(default=0)
    # Car Emission - Company Vehicles
    company_gasoline_car_emissions = models.FloatField(default=0)
    company_diesel_car_emissions = models.FloatField(default=0)
    company_electric_car_emissions = models.FloatField(default=0)
    company_hybrid_car_emissions = models.FloatField(default=0)

    # Car Emission - Staff Commute
    staff_gasoline_car_emissions = models.FloatField(default=0)
    staff_diesel_car_emissions = models.FloatField(default=0)
    staff_electric_car_emissions = models.FloatField(default=0)
    staff_hybrid_car_emissions = models.FloatField(default=0)

    vehicle_footprint = models.FloatField(default=0)
    emission_unit = models.CharField(
        max_length=12,
        choices=CO2EmissionUnit.choices,
        default=CO2EmissionUnit.TCO2,
        blank=False,
    )

    def save(self, *args, **kwargs):
        self.flight_emission = (
            self.flight_distance
            * BUSINESS_FLIGHT_DISTANCE_CONVERSION_FACTORS[self.flight_unit]
        )
        self.public_transit_emission = (
            self.public_transit_distance
            * BUSINESS_PUBLIC_TRNSIT_CONVERSION_FACTORS[self.transit_unit]
        )

        self.company_gasoline_car_emissions = (
            self.company_gasoline_car_driven
            * BUSINESS_GASOLINE_CAR_EMISSIONS_PER_KM[self.gasolin_car_unit]
        ) + BUSINESS_GASOLINE_CAR_MANUFACTURING_EMISSIONS[self.gasolin_car_unit]

        self.company_diesel_car_emissions = (
            self.company_diesel_car_driven
            * BUSINESS_DISEL_CAR_EMISSIONS_PER_KM[self.diesel_car_unit]
        ) + BUSINESS_DIESEL_CAR_MANUFACTURING_EMISSIONS[self.diesel_car_unit]

        self.company_electric_car_emissions = (
            BUSINESS_ELECTRIC_CAR_EMISSIONS_PER_KM[self.electric_car_unit]
            * self.company_electric_car_driven
        ) + BUSINESS_ELECTRIC_CAR_MANUFACTURING_EMISSIONS[self.electric_car_unit]
        self.company_hybrid_car_emissions = (
            BUSINESS_HYBRID_CAR_EMISSIONS_PER_KM[self.hybrid_car_unit]
            * self.company_hybrid_car_driven
        ) + BUSINESS_HYBRID_CAR_MANUFACTURING_EMISSIONS[self.hybrid_car_unit]

        self.staff_gasoline_car_emissions = (
            self.staff_gasoline_car_driven
            * STAFF_GASOLINE_CAR_EMISSIONS_PER_KM[self.gasolin_car_unit]
        )
        self.staff_diesel_car_emissions = (
            self.staff_diesel_car_driven
            * STAFF_DISEL_CAR_EMISSIONS_PER_KM[self.diesel_car_unit]
        )

        self.staff_electric_car_emissions = (
            self.staff_electric_car_driven
            * STAFF_ELECTRIC_CAR_EMISSIONS_PER_KM[self.electric_car_unit]
        )
        self.staff_hybrid_car_emissions = (
            self.staff_hybrid_car_driven
            * STAFF_HYBRID_CAR_EMISSIONS_PER_KM[self.hybrid_car_unit]
        )
        self.vehicle_footprint = (
            self.flight_emission
            + self.public_transit_emission
            + self.company_gasoline_car_emissions
            + self.company_diesel_car_emissions
            + self.company_electric_car_emissions
            + self.company_hybrid_car_emissions
            + self.staff_gasoline_car_emissions
            + self.staff_diesel_car_emissions
            + self.staff_electric_car_emissions
            + self.staff_hybrid_car_emissions
        )
        super().save(*args, **kwargs)

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse(
            "travel:detail", kwargs={"pk": self.pk}
        )  # f"/transportation/{self.pk}"

ECOLENS/ecolens/food/forms.py
from django import forms
from .models import FoodConsumption

DIET_CATEGORY_CHOICES = (
    ("VI", "Vegan"),
    ("VG", "Vegetarian"),
    ("FL", "Flexitarian"),
    ("OM", "Omnivore"),
)

EMISSION_CHOICES = ("TCO2_Y", "tCO2equ/year")


class HouseholdeUsagesForm(forms.ModelForm):

    diet_type = forms.ChoiceField(
        choices=DIET_CATEGORY_CHOICES,
        required=True,
        initial=DIET_CATEGORY_CHOICES[0],
        error_messages={
            "required": "Please select a Unit.",
            "invalid_choice": "Invalid Unit choice.",
        },
    )
    consumption_level = (
        forms.DecimalField(
            min_value=0,
            max_value=1.0,
            max_digits=3,
            decimal_places=2,
            initial=0,
        ),
    )
    consumption_unit = forms.ChoiceField(
        choices=EMISSION_CHOICES,
        required=True,
        initial=EMISSION_CHOICES[0],
        error_messages={
            "required": "Please select a Unit.",
            "invalid_choice": "Invalid Unit choice.",
        },
    )

    class Meta:
        model = FoodConsumption
        # Limit the input fields
        fields = [
            "diet_type",
            "consumption_level",
            "level_of_wastage",
            "consumption_unit",
        ]

    def clean(self):
        value = self.cleaned_data
        return value

ECOLENS/ecolens/food/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse

# Create your views here.
from .models import FoodConsumption

# from .forms import VehicleUsagesForm
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.messages.views import SuccessMessageMixin

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages

from general.models import General

from django.db.models.signals import pre_save
from django.dispatch import receiver


# @method_decorator(login_required, name="dispatch")
class FoodConsumptionCreateView(SuccessMessageMixin, CreateView):
    model = FoodConsumption
    # ristrict field input
    fields = [
        "diet_type",
        "consumption_level",
        "level_of_wastage",
        "consumption_unit",
        "general",
    ]
    # fields = "__all__"

    success_url = reverse_lazy("food:food_consumption_list")
    # template_name = "books/update.html"
    success_message = "Created successfully!"

    def get(self, request, *args, **kwargs):
        # Check if a condition is met and redirect if necessary

        if not General.objects.count():
            messages.warning(self.request, "Your object has need to be created yet.")
            return redirect(reverse_lazy("general:general_create"))

        return super().get(request, *args, **kwargs)

    # def render_to_response(self, context, **response_kwargs):
    #     general = General.objects.count()
    #     print(f"general:{general}")
    #     if general <= 0:
    #         print("general is empty!")
    #         messages.success(self.request, "Your object has need to be created first.")
    #         return redirect(reverse_lazy("general:general_create"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Food Consumption create"
        context["heading"] = "Food Consumption"
        return context


class FoodConsumptionListView(ListView):
    paginate_by = 5  # Adjust the number of items per page
    model = FoodConsumption

    def get_queryset(self):
        # '-' indicates descending order
        # order = self.request.GET.get("orderby", "-updated_at")
        order = self.request.GET.get("orderby", "id")
        new_context = FoodConsumption.objects.order_by(order)

        return new_context

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context["paginator"]
        # page = context["page"]
        # Add additional context variables as needed
        context["title"] = "Food Consumption list"
        context["heading"] = "Food Consumption list"
        return context


class FoodConsumptionDetailView(DetailView):
    model = FoodConsumption

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Detail"
        context["heading"] = "Food Consumption"
        return context


class FoodConsumptionUpdateView(UpdateView):
    model = FoodConsumption
    fields = [
        "diet_type",
        "consumption_level",
        "level_of_wastage",
        "consumption_unit",
        "general",
    ]
    template_name_suffix = "_update_form"
    success_url = reverse_lazy("food:food_consumption_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Update"
        context["heading"] = "Update food consumption"
        return context


class FoodConsumptionDeleteView(SuccessMessageMixin, DeleteView):
    model = FoodConsumption

    def get_success_url(self):
        messages.success(self.request, "deleted successfully")
        return reverse_lazy("food:food_consumption_list")

ECOLENS/ecolens/food/templates/food/foodconsumption_confirm_delete.html
{% extends "includes/base.html" %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form> 

{% endblock %}

ECOLENS/ecolens/food/templates/food/foodconsumption_detail.html
{% extends "includes/base.html" %}

{% block content %}


<h3>{{heading|upper}}</h3>
  <div class="card-deck">
        <div class="card border-info mb-3" style="max-width: 40rem;">
          <div class="card-header text-center" data-toggle="tooltip" data-placement="top" title="FOOD CONSUMPTION">
            <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-egg-fried" viewBox="0 0 16 16">
              <path d="M8 11a3 3 0 1 0 0-6 3 3 0 0 0 0 6"/>
              <path d="M13.997 5.17a5 5 0 0 0-8.101-4.09A5 5 0 0 0 1.28 9.342a5 5 0 0 0 8.336 5.109 3.5 3.5 0 0 0 5.201-4.065 3.001 3.001 0 0 0-.822-5.216zm-1-.034a1 1 0 0 0 .668.977 2.001 2.001 0 0 1 .547 3.478 1 1 0 0 0-.341 1.113 2.5 2.5 0 0 1-3.715 2.905 1 1 0 0 0-1.262.152 4 4 0 0 1-6.67-4.087 1 1 0 0 0-.2-1 4 4 0 0 1 3.693-6.61 1 1 0 0 0 .8-.2 4 4 0 0 1 6.48 3.273z"/>
            </svg> 
          </div>
          <div class="card-body text-info align-items-center">
            <h5 class="card-title">Diet: {{object.get_diet_type_display}}</h5>
            <li>
              CONSUMPTION LEVEL : {{object.consumption_level}} {{object.consumption_unit}}
            </li>
          
            <p class="card-text">
              EMISSION :<span class="emission"> {{object.diet_emission|floatformat:4}}</span> 
              <strong>{{object.diet_emission_unit}}</strong>
            </p>
          </div>
        </div>

        <div class="card border-info mb-3" style="max-width: 90rem;">
          <div class="card-header text-center" data-toggle="tooltip" data-placement="top" title="FOOD WASTE">
            <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-trash2" viewBox="0 0 16 16">
              <path d="M14 3a.7.7 0 0 1-.037.225l-1.684 10.104A2 2 0 0 1 10.305 15H5.694a2 2 0 0 1-1.973-1.671L2.037 3.225A.7.7 0 0 1 2 3c0-1.105 2.686-2 6-2s6 .895 6 2M3.215 4.207l1.493 8.957a1 1 0 0 0 .986.836h4.612a1 1 0 0 0 .986-.836l1.493-8.957C11.69 4.689 9.954 5 8 5s-3.69-.311-4.785-.793"/>
            </svg>
          </div>
          <div class="card-body text-info align-items-center">
            <h5 class="card-title">LEVEL OF WASTAGE : {{object.get_level_of_wastage_display}} {{object.consumption_unit}}</h5>
            <p class="card-text">
              EMISSION : <span class="emission">{{object.wastage_emission|floatformat:4}}</span> 
              <strong>{{object.wastage_emission_unit}}</strong>
            </p>
          </div>
        </div>
</div>



<div class="card-deck">
  <div class="card border-info mb-3" style="max-width: 40rem;">
    <div class="card-header text-center" data-toggle="tooltip" data-placement="top" title="FOOD CONSUMPTION">
      <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-egg" viewBox="0 0 16 16">
        <path d="M8 15a5 5 0 0 1-5-5c0-1.956.69-4.286 1.742-6.12.524-.913 1.112-1.658 1.704-2.164C7.044 1.206 7.572 1 8 1s.956.206 1.554.716c.592.506 1.18 1.251 1.704 2.164C12.31 5.714 13 8.044 13 10a5 5 0 0 1-5 5m0 1a6 6 0 0 0 6-6c0-4.314-3-10-6-10S2 5.686 2 10a6 6 0 0 0 6 6"/>
      </svg>
    </div>
    <div class="card-body text-info align-items-center">
      <h5 class="card-title">FOOD FOOTPRINT</h5>
        <p> <span class="emission">{{object.food_footprint|floatformat:4}}</span> {{object.food_footprint_unit}}
        </p>
        
      </p>
    </div>
  </div>
</div>

{% endblock %}

ECOLENS/ecolens/food/templates/food/foodconsumption_form.html
{% extends "includes/base.html" %}

{% block content %}
{% if messages %}
{% for message in messages %}
<div class="text-center alert alert-{{ message.tags }}">
    {{ message|safe }}
</div>
{% endfor %}
{% endif %}

<div class="row">
    <h4>{{ heading|capfirst }}</h4>
</div>

<div class="col-sm-8 align-items-center">
    <form method="post">{% csrf_token %}
        <div class="col-auto">
            {{ form.as_p }}
        </div>
        <button type="submit" class="btn btn-primary" value="Save">Save</button>
    </form>
</div>
{% endblock %}

ECOLENS/ecolens/food/templates/food/foodconsumption_update_form.html
{% extends "includes/base.html" %}

{% block content %}
<div class="row">
    <h4>{{ heading|capfirst }}</h4>
</div>
<div class="row g-3 align-items-center">

<form method="post">{% csrf_token %}
    <div class="col-auto">
        {{ form.as_p }}
    </div>
    <button type="submit" class="btn btn-primary">Update</button>
</div>
</form>
</div>
{% endblock %}