ECOLENS/ecolens/ecolens/urls.py
from django.contrib import admin
from django.urls import include, path

from .views import home_view, about_view

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("", home_view, name="home"),
    path("about/", about_view, name="about"),
    path("vehicle_usages/", include("vehicle_usages.urls")),
    path("household_usages/", include("household.urls")),
    path("food/", include("food.urls")),
    path("carbon_footprint/", include("carbon_footprint.urls")),
    path("consumer_good/", include("consumer_good.urls")),
    path("other/", include("other.urls")),
    path("travel/", include("travel.urls")),
    path("", include("general.urls")),
    path("accounts/", include("accounts.urls")),
]

ECOLENS/ecolens/food/urls.py
from django.urls import path
from food.views import (
    # calss based views
    FoodConsumptionCreateView,
    FoodConsumptionDetailView,
    FoodConsumptionListView,
    FoodConsumptionUpdateView,
    FoodConsumptionDeleteView,
)


app_name = "food"
urlpatterns = [
    path(
        "",
        FoodConsumptionListView.as_view(),
        name="food_consumption_list",
    ),
    path(
        "<int:pk>",
        FoodConsumptionDetailView.as_view(),
        name="detail",
    ),
    path(
        "create",
        FoodConsumptionCreateView.as_view(),
        name="food_consumption_create",
    ),
    path(
        "<int:pk>/update",
        FoodConsumptionUpdateView.as_view(),
        name="household_consumption_update",
    ),
    path(
        "<int:pk>/delete",
        FoodConsumptionDeleteView.as_view(),
        name="household_consumption_delete",
    ),
]

ECOLENS/ecolens/travel/urls.py
from django.urls import path
from .views import (
    # calss based views
    TransportationListView,
    TransportationCreateView,
    TransportationDetailView,
    TransportationUpdateView,
    TransportationDeleteView,
)


app_name = "travel"
urlpatterns = [
    path(
        "",
        TransportationListView.as_view(),
        name="travel_list",
    ),
    path(
        "<int:pk>",
        TransportationDetailView.as_view(),
        name="detail",
    ),
    path(
        "create",
        TransportationCreateView.as_view(),
        name="travel_create",
    ),
    path(
        "<int:pk>/update",
        TransportationUpdateView.as_view(),
        name="travel_update",
    ),
    path(
        "<int:pk>/delete",
        TransportationDeleteView.as_view(),
        name="vehicle_usages_delete",
    ),
]

ECOLENS/ecolens/travel/models.py
# from django.db import models

# Create your models here.
from django.db import models
from django.utils import timezone

from django.db import models
from django.utils import timezone
from django.urls import reverse
from ecolens.custom_choices import DistanceUnit, CO2EmissionUnit
from ecolens.custom_validators import validate_min, validate_distance_unit
from .utils import (
    BUSINESS_FLIGHT_DISTANCE_CONVERSION_FACTORS,
    BUSINESS_PUBLIC_TRNSIT_CONVERSION_FACTORS,
    BUSINESS_GASOLINE_CAR_MANUFACTURING_EMISSIONS,
    BUSINESS_DIESEL_CAR_MANUFACTURING_EMISSIONS,
    BUSINESS_ELECTRIC_CAR_MANUFACTURING_EMISSIONS,
    BUSINESS_HYBRID_CAR_MANUFACTURING_EMISSIONS,
    BUSINESS_ELECTRIC_CAR_EMISSIONS_PER_KM,
    BUSINESS_HYBRID_CAR_EMISSIONS_PER_KM,
    BUSINESS_GASOLINE_CAR_EMISSIONS_PER_KM,
    BUSINESS_DISEL_CAR_EMISSIONS_PER_KM,
    BUSINESS_ELECTRIC_CAR_EMISSIONS_PER_KM,
    BUSINESS_HYBRID_CAR_EMISSIONS_PER_KM,
    STAFF_GASOLINE_CAR_EMISSIONS_PER_KM,
    STAFF_DISEL_CAR_EMISSIONS_PER_KM,
    STAFF_ELECTRIC_CAR_EMISSIONS_PER_KM,
    STAFF_HYBRID_CAR_EMISSIONS_PER_KM,
)


class Transport(models.Model):
    id = models.AutoField(primary_key=True)
    flight_distance = models.FloatField(
        default=0,
        validators=[validate_min],
        help_text="e.g., 1000",
    )
    flight_unit = models.CharField(
        max_length=2,
        choices=DistanceUnit.choices,
        default=DistanceUnit.Km,
        blank=False,
        validators=[validate_distance_unit],
    )

    public_transit_distance = models.FloatField(
        default=0,
        validators=[validate_min],
        help_text="e.g., 1000",
    )
    transit_unit = models.CharField(
        max_length=2,
        choices=DistanceUnit.choices,
        default=DistanceUnit.Km,
        blank=False,
        validators=[validate_distance_unit],
    )

    # No of cars- Company Vehicles
    company_num_of_gasolin_cars = models.IntegerField(default=0, help_text="e.g., 1")
    company_num_of_diesel_cars = models.IntegerField(default=0, help_text="e.g., 1")
    company_num_of_electric_cars = models.IntegerField(default=0, help_text="e.g., 1")
    company_num_of_hybrid_cars = models.IntegerField(default=0, help_text="e.g., 1")

    # Car Milage - Company Vehicles
    company_gasoline_car_driven = models.FloatField(default=0, help_text="e.g., 100")
    company_diesel_car_driven = models.FloatField(default=0, help_text="e.g., 100")
    company_electric_car_driven = models.FloatField(default=0, help_text="e.g., 100")
    company_hybrid_car_driven = models.FloatField(default=0, help_text="e.g., 100")

    # Car Milage - Staff Commute
    staff_gasoline_car_driven = models.FloatField(default=0, help_text="e.g., 100")
    staff_diesel_car_driven = models.FloatField(default=0, help_text="e.g., 100")
    staff_electric_car_driven = models.FloatField(default=0, help_text="e.g., 100")
    staff_hybrid_car_driven = models.FloatField(default=0, help_text="e.g., 100")

    # Car Milage Unit - Company Vehicles
    gasolin_car_unit = models.CharField(
        max_length=2,
        choices=DistanceUnit.choices,
        default=DistanceUnit.Km,
        blank=False,
        validators=[validate_distance_unit],
    )
    diesel_car_unit = models.CharField(
        max_length=2,
        choices=DistanceUnit.choices,
        default=DistanceUnit.Km,
        blank=False,
        validators=[validate_distance_unit],
    )
    electric_car_unit = models.CharField(
        max_length=2,
        choices=DistanceUnit.choices,
        default=DistanceUnit.Km,
        blank=False,
        validators=[validate_distance_unit],
    )
    hybrid_car_unit = models.CharField(
        max_length=2,
        choices=DistanceUnit.choices,
        default=DistanceUnit.Km,
        blank=False,
        validators=[validate_distance_unit],
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # CALCULATED FILDS
    flight_emission = models.FloatField(default=0)
    public_transit_emission = models.FloatField(default=0)
    # Car Emission - Company Vehicles
    company_gasoline_car_emissions = models.FloatField(default=0)
    company_diesel_car_emissions = models.FloatField(default=0)
    company_electric_car_emissions = models.FloatField(default=0)
    company_hybrid_car_emissions = models.FloatField(default=0)

    # Car Emission - Staff Commute
    staff_gasoline_car_emissions = models.FloatField(default=0)
    staff_diesel_car_emissions = models.FloatField(default=0)
    staff_electric_car_emissions = models.FloatField(default=0)
    staff_hybrid_car_emissions = models.FloatField(default=0)

    vehicle_footprint = models.FloatField(default=0)
    emission_unit = models.CharField(
        max_length=12,
        choices=CO2EmissionUnit.choices,
        default=CO2EmissionUnit.TCO2,
        blank=False,
    )

    def save(self, *args, **kwargs):
        self.flight_emission = (
            self.flight_distance
            * BUSINESS_FLIGHT_DISTANCE_CONVERSION_FACTORS[self.flight_unit]
        )
        self.public_transit_emission = (
            self.public_transit_distance
            * BUSINESS_PUBLIC_TRNSIT_CONVERSION_FACTORS[self.transit_unit]
        )

        self.company_gasoline_car_emissions = (
            self.company_gasoline_car_driven
            * BUSINESS_GASOLINE_CAR_EMISSIONS_PER_KM[self.gasolin_car_unit]
        ) + BUSINESS_GASOLINE_CAR_MANUFACTURING_EMISSIONS[self.gasolin_car_unit]

        self.company_diesel_car_emissions = (
            self.company_diesel_car_driven
            * BUSINESS_DISEL_CAR_EMISSIONS_PER_KM[self.diesel_car_unit]
        ) + BUSINESS_DIESEL_CAR_MANUFACTURING_EMISSIONS[self.diesel_car_unit]

        self.company_electric_car_emissions = (
            BUSINESS_ELECTRIC_CAR_EMISSIONS_PER_KM[self.electric_car_unit]
            * self.company_electric_car_driven
        ) + BUSINESS_ELECTRIC_CAR_MANUFACTURING_EMISSIONS[self.electric_car_unit]
        self.company_hybrid_car_emissions = (
            BUSINESS_HYBRID_CAR_EMISSIONS_PER_KM[self.hybrid_car_unit]
            * self.company_hybrid_car_driven
        ) + BUSINESS_HYBRID_CAR_MANUFACTURING_EMISSIONS[self.hybrid_car_unit]

        self.staff_gasoline_car_emissions = (
            self.staff_gasoline_car_driven
            * STAFF_GASOLINE_CAR_EMISSIONS_PER_KM[self.gasolin_car_unit]
        )
        self.staff_diesel_car_emissions = (
            self.staff_diesel_car_driven
            * STAFF_DISEL_CAR_EMISSIONS_PER_KM[self.diesel_car_unit]
        )

        self.staff_electric_car_emissions = (
            self.staff_electric_car_driven
            * STAFF_ELECTRIC_CAR_EMISSIONS_PER_KM[self.electric_car_unit]
        )
        self.staff_hybrid_car_emissions = (
            self.staff_hybrid_car_driven
            * STAFF_HYBRID_CAR_EMISSIONS_PER_KM[self.hybrid_car_unit]
        )
        self.vehicle_footprint = (
            self.flight_emission
            + self.public_transit_emission
            + self.company_gasoline_car_emissions
            + self.company_diesel_car_emissions
            + self.company_electric_car_emissions
            + self.company_hybrid_car_emissions
            + self.staff_gasoline_car_emissions
            + self.staff_diesel_car_emissions
            + self.staff_electric_car_emissions
            + self.staff_hybrid_car_emissions
        )
        super().save(*args, **kwargs)

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse(
            "travel:detail", kwargs={"pk": self.pk}
        )  # f"/transportation/{self.pk}"

ECOLENS/ecolens/travel/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse

# Create your views here.
from .models import Transport
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.messages.views import SuccessMessageMixin

# from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

# from django.contrib.auth.decorators import login_required

# Create Class based views here.


# @method_decorator(login_required, name="dispatch")
class TransportationCreateView(SuccessMessageMixin, CreateView):
    # form_class = VehicleUsagesForm
    model = Transport
    # ristrict field input
    fields = [
        "flight_distance",
        "flight_unit",
        "public_transit_distance",
        "transit_unit",
        "company_num_of_gasolin_cars",
        "company_num_of_diesel_cars",
        "company_num_of_electric_cars",
        "company_num_of_hybrid_cars",
        "company_gasoline_car_driven",
        "staff_gasoline_car_driven",
        "gasolin_car_unit",
        "company_diesel_car_driven",
        "staff_diesel_car_driven",
        "diesel_car_unit",
        "company_electric_car_driven",
        "staff_electric_car_driven",
        "electric_car_unit",
        "company_hybrid_car_driven",
        "staff_hybrid_car_driven",
        "hybrid_car_unit",
    ]
    # fields = "__all__"

    success_url = reverse_lazy("travel:travel_list")
    # template_name = "books/update.html"
    success_message = "Created successfully!"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Transportation create"
        context["heading"] = "Transportation Usages Create"
        return context


class TransportationListView(ListView):
    paginate_by = 5  # Adjust the number of items per page
    model = Transport

    def get_queryset(self):
        # '-' indicates descending order
        order = self.request.GET.get("orderby", "-updated_at")
        new_context = Transport.objects.order_by(order)

        return new_context

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context["paginator"]
        # page = context["page"]
        # Add additional context variables as needed
        context["title"] = "Transportation  list"
        context["heading"] = "Transportation list"
        return context


class TransportationDetailView(DetailView):
    model = Transport

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Detail"
        context["heading"] = "Transportation usages"
        return context


class TransportationUpdateView(UpdateView):
    model = Transport
    fields = [
        "flight_distance",
        "flight_unit",
        "public_transit_distance",
        "transit_unit",
        "company_num_of_gasolin_cars",
        "company_num_of_diesel_cars",
        "company_num_of_electric_cars",
        "company_num_of_hybrid_cars",
        "company_gasoline_car_driven",
        "staff_gasoline_car_driven",
        "gasolin_car_unit",
        "company_diesel_car_driven",
        "staff_diesel_car_driven",
        "diesel_car_unit",
        "company_electric_car_driven",
        "staff_electric_car_driven",
        "electric_car_unit",
        "company_hybrid_car_driven",
        "staff_hybrid_car_driven",
        "hybrid_car_unit",
    ]
    template_name_suffix = "_update_form"
    success_url = reverse_lazy("travel:travel_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Update"
        context["heading"] = "Update Transportaion usages"
        return context


class TransportationDeleteView(DeleteView):
    model = Transport
    success_url = reverse_lazy("travel:travel_list")

ECOLENS/ecolens/travel/templates/travel/transport_confirm_delete.html
{% extends "includes/base.html" %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form> 

{% endblock %}

ECOLENS/ecolens/travel/templates/travel/transport_form.html
{% extends "includes/base.html" %}

{% block content %}
{% if messages %}
{% for message in messages %}
<div class="text-center alert alert-{{ message.tags }}">
    {{ message|safe }}
</div>
{% endfor %}
{% endif %}

<div class="row">
    <h4>{{ heading|capfirst }}</h4>
</div>

<div class="col-sm-8 align-items-center">
    <form method="post">{% csrf_token %}
        <div class="col-auto">
            {{ form.as_p }}
        </div>
        <button type="submit" class="btn btn-primary" value="Save">Save</button>
    </form>
</div>
{% endblock %}

ECOLENS/ecolens/travel/templates/travel/transport_list.html
{% extends "includes/base.html" %}

{% block content %}

{% if messages %}
     {% for message in messages %}
         <div class="text-center alert alert-{{ message.tags }}" role="alert">
             {{ message|safe }}
         </div>
     {% endfor %}
 {% endif %}


 <div class="justify-content-center">
  <h4>{{ heading|capfirst }}</h4>
</div>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-circle" viewBox="0 0 16 16">
          <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>
          <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0"/>
        </svg>
      </th>
      <!-- <th scope="col"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-airplane-engines" viewBox="0 0 16 16">
        <path d="M8 0c-.787 0-1.292.592-1.572 1.151A4.35 4.35 0 0 0 6 3v3.691l-2 1V7.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.191l-1.17.585A1.5 1.5 0 0 0 0 10.618V12a.5.5 0 0 0 .582.493l1.631-.272.313.937a.5.5 0 0 0 .948 0l.405-1.214 2.21-.369.375 2.253-1.318 1.318A.5.5 0 0 0 5.5 16h5a.5.5 0 0 0 .354-.854l-1.318-1.318.375-2.253 2.21.369.405 1.214a.5.5 0 0 0 .948 0l.313-.937 1.63.272A.5.5 0 0 0 16 12v-1.382a1.5 1.5 0 0 0-.83-1.342L14 8.691V7.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v.191l-2-1V3c0-.568-.14-1.271-.428-1.849C9.292.591 8.787 0 8 0M7 3c0-.432.11-.979.322-1.401C7.542 1.159 7.787 1 8 1s.458.158.678.599C8.889 2.02 9 2.569 9 3v4a.5.5 0 0 0 .276.447l5.448 2.724a.5.5 0 0 1 .276.447v.792l-5.418-.903a.5.5 0 0 0-.575.41l-.5 3a.5.5 0 0 0 .14.437l.646.646H6.707l.647-.646a.5.5 0 0 0 .14-.436l-.5-3a.5.5 0 0 0-.576-.411L1 11.41v-.792a.5.5 0 0 1 .276-.447l5.448-2.724A.5.5 0 0 0 7 7z"/>
      </svg></th>
      <th scope="col"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bus-front" viewBox="0 0 16 16">
        <path d="M5 11a1 1 0 1 1-2 0 1 1 0 0 1 2 0m8 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0m-6-1a1 1 0 1 0 0 2h2a1 1 0 1 0 0-2zm1-6c-1.876 0-3.426.109-4.552.226A.5.5 0 0 0 3 4.723v3.554a.5.5 0 0 0 .448.497C4.574 8.891 6.124 9 8 9s3.426-.109 4.552-.226A.5.5 0 0 0 13 8.277V4.723a.5.5 0 0 0-.448-.497A44 44 0 0 0 8 4m0-1c-1.837 0-3.353.107-4.448.22a.5.5 0 1 1-.104-.994A44 44 0 0 1 8 2c1.876 0 3.426.109 4.552.226a.5.5 0 1 1-.104.994A43 43 0 0 0 8 3"/>
        <path d="M15 8a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1V2.64c0-1.188-.845-2.232-2.064-2.372A44 44 0 0 0 8 0C5.9 0 4.208.136 3.064.268 1.845.408 1 1.452 1 2.64V4a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1v3.5c0 .818.393 1.544 1 2v2a.5.5 0 0 0 .5.5h2a.5.5 0 0 0 .5-.5V14h6v1.5a.5.5 0 0 0 .5.5h2a.5.5 0 0 0 .5-.5v-2c.607-.456 1-1.182 1-2zM8 1c2.056 0 3.71.134 4.822.261.676.078 1.178.66 1.178 1.379v8.86a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 11.5V2.64c0-.72.502-1.301 1.178-1.379A43 43 0 0 1 8 1"/>
      </svg></th> -->

      <!-- <th scope="col">Update</th> -->
     <th>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
        <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325"/>
      </svg>
    </th>
      <!-- <span class="glyphicon">&#x270f;</span> -->
  
      <!-- <th scope="col">delete</th> -->
       <th>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash2" viewBox="0 0 16 16">
          <path d="M14 3a.7.7 0 0 1-.037.225l-1.684 10.104A2 2 0 0 1 10.305 15H5.694a2 2 0 0 1-1.973-1.671L2.037 3.225A.7.7 0 0 1 2 3c0-1.105 2.686-2 6-2s6 .895 6 2M3.215 4.207l1.493 8.957a1 1 0 0 0 .986.836h4.612a1 1 0 0 0 .986-.836l1.493-8.957C11.69 4.689 9.954 5 8 5s-3.69-.311-4.785-.793"/>
        </svg>
      </th>

    </tr>
  </thead>
  <tbody >
  

    {% for object in object_list %}
    
    <tr>

      <td><a class="nav-link" href="{{object.get_absolute_url}}">{{object.pk}}</a></td>
      <!-- <td>{{object.flight_distance}} {{object.get_flight_unit_display}} </td>
      <td>{{object.public_transit_distance}} {{object.get_transit_unit_display}} </td>
      -->
      <td><a class="nav-link" href="{{object.get_absolute_url}}/update">{{object.pk}}</a></td>
      <td><a class="nav-link" href="{{object.get_absolute_url}}/delete">{{object.pk}}</a></td>
    </tr> 
    {% endfor %}

   
  </tbody>
  </table>

  <!-- pagination starts-->

  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
          <li class="page-item"> 
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
          </li>
          {% else %}
          <li class="page-item disabled"> 
            <a class="page-link" href="#">Previous</a>
          </li>
        {% endif %}
          <li class="page-item active"> 
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a>
          </li>
        {% if page_obj.has_next %}
          <li class="page-item"> 
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
          </li>

          {% else %}
          <li class="page-item disabled"> 
            <a class="page-link" href="#">Next</a>
          </li>
        {% endif %}
    </ul>
  </nav>
  <!-- pagination ends-->

{% endblock %}

ECOLENS/ecolens/travel/templates/travel/transport_update_form.html
{% extends "includes/base.html" %}

{% block content %}
<div class="row">
    <h4>{{ heading|capfirst }}</h4>
</div>
<div class="row g-3 align-items-center">

<form method="post">{% csrf_token %}
    <div class="col-auto">
        {{ form.as_p }}
    </div>
    <button type="submit" class="btn btn-primary">Update</button>
</div>
</form>
</div>
{% endblock %}